### ISSUE TITLE
Autorisation problem

### ISSUE THREAD

**Issue by Caniaris** [ManOnDaMoon/omeka-s-module-RestrictedSites#3]
Hello,
I installed Omeka s V1.1.1
I installed the following plugin : Guest User version 0.1.2 and RestrictedSites latest version.
I created a site and I specified a user in “user’s permissions” on the control panel of the site as “user”.
When this user tries to connect to omeka, the connection is successful but it is impossible to access to the informations of the site.
This error appears :

Omeka\Mvc\Exception\PermissionDeniedException: Autorisation refusée à l’utilisateur actuel d’accéder à l’action browse du contrôleur Omeka\Controller\Admin\Index. in /srv/data/web/vhosts/XXX.com/htdocs/omeka/application/src/Mvc/MvcListeners.php:436
Stack trace:
#0 /srv/data/web/vhosts/XXX.com/htdocs/omeka/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Omeka\Mvc\MvcListeners->authorizeUserAgainstController(Object(Zend\Mvc\MvcEvent))
#1 /srv/data/web/vhosts/XXX.com/htdocs/omeka/vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#2 /srv/data/web/vhosts/XXX.com/htdocs/omeka/vendor/zendframework/zend-mvc/src/Application.php(332): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#3 /srv/data/web/vhosts/XXX.com/htdocs/omeka/index.php(21): Zend\Mvc\Application->run()
#4 {main}

I admit that I reach my limits of comprehension of Omeka.
Does anyone has an idea?
Thanks a lot
Yoann

**Comment by ManOnDaMoon** [comment]
Bonjour Yoann

J’ai vu ton sujet sur le forum Omeka.
L’erreur indiquée sous-entend que tu tentes d’acceder à l’interface d’admin avec l’utilisateur invité que tu as créé. Il peut s’agir d’une redirection malheureuse.

Juste pour être certain : peux-tu décrire quelle configuration est en place et quelles URLs tu visites pour obtenir l’erreur ? Des captures d’ecran aideraient aussi.

Merci et bonne soirée.

Laurent

**Comment by Caniaris** [comment]
Bonjour Laurent et merci de prendre le temps de te pencher sur mon probleme.
Voici ma configuration :
 Omeka S V1.1.1
Les modules suivants : 
Advanced Search Plus version 3.0.1
CSV Import version 1.1.0 
Custom Ontology version 3.0.2
File Sideload version 1.0.1
Folksonomy version 3.3.8
Group version 3.0.2 
Guest User version 0.1.2
Hide Properties version 1.0.0
Metadata Browse version 1.1.2
Reference version 3.4.10
RestrictedSites version 0.6 
Rights Statements version 0.2.0
Search version 0.4.0
Value Suggest version 1.1.0

Lorsque je tape l'URL : http://XXX.com/omeka/login
Je rentre login et mdp
L'URL devient http://XXX.com/omeka/admin
Et j'ai ce message d'erreur:

    Connexion réussie
Omeka S rencontre une erreur
Omeka\Mvc\Exception\PermissionDeniedException: Autorisation refusée à l’utilisateur actuel d’accéder à l’action browse du contrôleur Omeka\Controller\Admin\Index. in /srv/data/web/vhosts/XXX.com/htdocs/omeka/application/src/Mvc/MvcListeners.php:436
Stack trace:
#0 /srv/data/web/vhosts/XXX.com/htdocs/omeka/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Omeka\Mvc\MvcListeners->authorizeUserAgainstController(Object(Zend\Mvc\MvcEvent))
#1 /srv/data/web/vhosts/XXX.com/htdocs/omeka/vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#2 /srv/data/web/vhosts/XXX.com/htdocs/omeka/vendor/zendframework/zend-mvc/src/Application.php(332): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#3 /srv/data/web/vhosts/XXX.com/htdocs/omeka/index.php(21): Zend\Mvc\Application->run()
#4 {main}

### Ensuite, quand je supprime "admin" de l'URL c'est a dire : http://XXX.com/omeka/
### J'ai le choix entre acceder au site auquel je veux acceder, auquel cas j'ai: 

Omeka S rencontre une erreur

Doctrine\ORM\EntityNotFoundException
Entity of type 'Omeka\Entity\Item' for IDs id(8374) was not found

Détails :

Doctrine\ORM\EntityNotFoundException: Entity of type 'Omeka\Entity\Item' for IDs id(8374) was not found in /srv/data/web/vhosts/XXX.com/htdocs/omeka/vendor/doctrine/orm/lib/Doctrine/ORM/EntityNotFoundException.php:47
Stack trace:
#0 /srv/data/web/vhosts/XXX.com/htdocs/omeka/vendor/doctrine/orm/lib/Doctrine/ORM/Proxy/ProxyFactory.php(196): Doctrine\ORM\EntityNotFoundException::fromClassNameAndIdentifier('Omeka\\Entity\\It...', Array)
#1 /srv/data/web/vhosts/XXX.com/htdocs/omeka/application/data/doctrine-proxies/__CG__OmekaEntityItem.php(208): Doctrine\ORM\Proxy\ProxyFactory->Doctrine\ORM\Proxy\{closure}(Object(DoctrineProxies\__CG__\Omeka\Entity\Item), 'getMedia', Array)
#2 /srv/data/web/vhosts/XXX.com/htdocs/omeka/application/data/doctrine-proxies/__CG__OmekaEntityItem.php(208): Closure->__invoke(Object(DoctrineProxies\__CG__\Omeka\Entity\Item), 'getMedia', Array)
#3 /srv/data/web/vhosts/XXX.com/htdocs/omeka/application/src/Api/Representation/ItemRepresentation.php(50): DoctrineProxies\__CG__\Omeka\Entity\Item->getMedia()
#4 /srv/data/web/vhosts/XXX.com/htdocs/omeka/application/src/Api/Representation/ItemRepresentation.php(78): Omeka\Api\Representation\ItemRepresentation->media()
#5 /srv/data/web/vhosts/XXX.com/htdocs/omeka/application/view/common/block-layout/item-showcase.phtml(9): Omeka\Api\Representation\ItemRepresentation->primaryMedia()
#6 /srv/data/web/vhosts/XXX.com/htdocs/omeka/vendor/zendframework/zend-view/src/Renderer/PhpRenderer.php(505): include('/srv/data/web/v...')
#7 /srv/data/web/vhosts/XXX.com/htdocs/omeka/vendor/zendframework/zend-view/src/Helper/Partial.php(61): Zend\View\Renderer\PhpRenderer->render(NULL, NULL)
#8 [internal function]: Zend\View\Helper\Partial->__invoke('common/block-la...', Array)
#9 /srv/data/web/vhosts/XXX.com/htdocs/omeka/vendor/zendframework/zend-view/src/Renderer/PhpRenderer.php(397): call_user_func_array(Object(Zend\View\Helper\Partial), Array)
#10 /srv/data/web/vhosts/XXX.com/htdocs/omeka/application/src/Site/BlockLayout/ItemShowcase.php(44): Zend\View\Renderer\PhpRenderer->__call('partial', Array)
#11 /srv/data/web/vhosts/XXX.com/htdocs/omeka/application/src/View/Helper/BlockLayout.php(124): Omeka\Site\BlockLayout\ItemShowcase->render(Object(Zend\View\Renderer\PhpRenderer), Object(Omeka\Api\Representation\SitePageBlockRepresentation))
#12 /srv/data/web/vhosts/XXX.com/htdocs/omeka/application/view/omeka/site/page/content.phtml(9): Omeka\View\Helper\BlockLayout->render(Object(Omeka\Api\Representation\SitePageBlockRepresentation))
#13 /srv/data/web/vhosts/XXX.com/htdocs/omeka/vendor/zendframework/zend-view/src/Renderer/PhpRenderer.php(505): include('/srv/data/web/v...')
#14 /srv/data/web/vhosts/XXX.com/htdocs/omeka/vendor/zendframework/zend-view/src/View.php(207): Zend\View\Renderer\PhpRenderer->render(NULL)
#15 /srv/data/web/vhosts/XXX.com/htdocs/omeka/vendor/zendframework/zend-view/src/View.php(236): Zend\View\View->render(Object(Zend\View\Model\ViewModel))
#16 /srv/data/web/vhosts/XXX.com/htdocs/omeka/vendor/zendframework/zend-view/src/View.php(200): Zend\View\View->renderChildren(Object(Zend\View\Model\ViewModel))
#17 /srv/data/web/vhosts/XXX.com/htdocs/omeka/vendor/zendframework/zend-view/src/View.php(236): Zend\View\View->render(Object(Zend\View\Model\ViewModel))
#18 /srv/data/web/vhosts/XXX.com/htdocs/omeka/vendor/zendframework/zend-view/src/View.php(200): Zend\View\View->renderChildren(Object(Zend\View\Model\ViewModel))
#19 /srv/data/web/vhosts/XXX.com/htdocs/omeka/vendor/zendframework/zend-mvc/src/View/Http/DefaultRenderingStrategy.php(105): Zend\View\View->render(Object(Zend\View\Model\ViewModel))
#20 /srv/data/web/vhosts/XXX.com/htdocs/omeka/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\View\Http\DefaultRenderingStrategy->render(Object(Zend\Mvc\MvcEvent))
#21 /srv/data/web/vhosts/XXX.com/htdocs/omeka/vendor/zendframework/zend-eventmanager/src/EventManager.php(171): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent))
#22 /srv/data/web/vhosts/XXX.com/htdocs/omeka/vendor/zendframework/zend-mvc/src/Application.php(367): Zend\EventManager\EventManager->triggerEvent(Object(Zend\Mvc\MvcEvent))
#23 /srv/data/web/vhosts/XXX.com/htdocs/omeka/vendor/zendframework/zend-mvc/src/Application.php(348): Zend\Mvc\Application->completeRequest(Object(Zend\Mvc\MvcEvent))
#24 /srv/data/web/vhosts/XXX.com/htdocs/omeka/index.php(21): Zend\Mvc\Application->run()
#25 {main}

### Ou acceder au tableau de bord et j'ai : 

 Omeka S rencontre une erreur

Omeka\Mvc\Exception\PermissionDeniedException
Autorisation refusée à l’utilisateur actuel d’accéder à l’action browse du contrôleur Omeka\Controller\Admin\Index.

Détails :

Omeka\Mvc\Exception\PermissionDeniedException: Autorisation refusée à l’utilisateur actuel d’accéder à l’action browse du contrôleur Omeka\Controller\Admin\Index. in /srv/data/web/vhosts/XXX.com/htdocs/omeka/application/src/Mvc/MvcListeners.php:436
Stack trace:
#0 /srv/data/web/vhosts/XXX.com/htdocs/omeka/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Omeka\Mvc\MvcListeners->authorizeUserAgainstController(Object(Zend\Mvc\MvcEvent))
#1 /srv/data/web/vhosts/XXX.com/htdocs/omeka/vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#2 /srv/data/web/vhosts/XXX.com/htdocs/omeka/vendor/zendframework/zend-mvc/src/Application.php(332): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#3 /srv/data/web/vhosts/XXX.com/htdocs/omeka/index.php(21): Zend\Mvc\Application->run()
#4 {main}

Voila, je n'ai pas fait de capture d'ecran mais j'ai retranscrit fidelement ce que j'ai.
Merci encore
Yoann

**Comment by ManOnDaMoon** [comment]
Merci c'est plus clair.
Je pars du principe que tu utilises un utilisateur "Guest", peux-tu me le confirmer ? 

Si c'est le cas voici quelques explications :

La première erreur `Autorisation refusée à l’utilisateur actuel d’accéder à l’action browse du contrôleur Omeka\Controller\Admin\Index` au login est normale : les utilisateurs "Guest" ne peuvent pas accéder à l'interface d'administration, donc se connecter via la page `xxx.com/omeka/login` renverra toujours cette erreur.
NB : la 3e erreur est exactement la même.
NB2 : Le plugin GuestUser n'est pas réellement utilisable "tout seul", il ajoute le rôle Guest pour que les autres modules puisse en profiter, comme le mien RestrictedSites.
Si tu as activé le module RestrictedSites dans les paramètres de ton site (cocher "Restrict access to site user list" et ajouter l'utilisateur dans les "Droits des utilisateurs"), tu devrais pouvoir t'identifier directement depuis le site en rentrant l'URL `xxx.com/omeka/sitelogin/monsite`. Dans ce cas tu devrais directement avoir l'erreur n°2.

La seconde erreur, donc, `Entity of type 'Omeka\Entity\Item' for IDs id(8374) was not found` est un problème différent, comme s'il manquait des éléments dans la base de donnée.
As-tu le même souci avec un utilisateur admin ?
En désactivant tous les modules et en les réactivant un par un, identifies-tu celui qui pourrait causer problème ?
Il serait pertinent d'ouvrir un nouveau sujet sur le forum Omeka juste avec cette erreur et la réponse à ces questions.

**Comment by Caniaris** [comment]
J'utilise en effet un utilisateur "guest"
Lorsque je rentre l'URL : xxx.com/omeka/sitelogin/monsite, jarrive en effet au probleme 2.
Meme probleme en admin avec cette reponse cette fois : 


 Zend\Router\Exception\InvalidArgumentException
Missing parameter "site-slug"

Détails :

Zend\Router\Exception\InvalidArgumentException: Missing parameter "site-slug" in /srv/data/web/vhosts/XXX.com/htdocs/omeka/vendor/zendframework/zend-router/src/Http/Segment.php:309
Stack trace:
#0 /srv/data/web/vhosts/XXX..com/htdocs/omeka/vendor/zendframework/zend-router/src/Http/Segment.php(423): Zend\Router\Http\Segment->buildPath(Array, Array, false, false, Array)
#1 /srv/data/web/vhosts/XXX..com/htdocs/omeka/vendor/zendframework/zend-router/src/Http/Part.php(206): Zend\Router\Http\Segment->assemble(Array, Array)
#2 /srv/data/web/vhosts/XXX..com/htdocs/omeka/vendor/zendframework/zend-router/src/Http/TreeRouteStack.php(391): Zend\Router\Http\Part->assemble(Array, Array)
#3 /srv/data/web/vhosts/XXX..com/htdocs/omeka/vendor/zendframework/zend-mvc/src/Controller/Plugin/Url.php(103): Zend\Router\Http\TreeRouteStack->assemble(Array, Array)
#4 /srv/data/web/vhosts/XXX..com/htdocs/omeka/vendor/zendframework/zend-mvc/src/Controller/Plugin/Redirect.php(50): Zend\Mvc\Controller\Plugin\Url->fromRoute('site', Array, Array, false)
#5 /srv/data/web/vhosts/XXX..com/htdocs/omeka/modules/RestrictedSites/src/Controller/Site/SiteLoginController.php(97): Zend\Mvc\Controller\Plugin\Redirect->toRoute('site')
#6 /srv/data/web/vhosts/XXX..com/htdocs/omeka/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(78): RestrictedSites\Controller\Site\SiteLoginController->loginAction()
#7 /srv/data/web/vhosts/XXX..com/htdocs/omeka/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#8 /srv/data/web/vhosts/XXX..com/htdocs/omeka/vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#9 /srv/data/web/vhosts/XXX..com/htdocs/omeka/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(106): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#10 /srv/data/web/vhosts/XXX..com/htdocs/omeka/vendor/zendframework/zend-mvc/src/DispatchListener.php(138): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#11 /srv/data/web/vhosts/XXX.com/htdocs/omeka/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#12 /srv/data/web/vhosts/XXX..com/htdocs/omeka/vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#13 /srv/data/web/vhosts/XXX.com/htdocs/omeka/vendor/zendframework/zend-mvc/src/Application.php(332): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#14 /srv/data/web/vhosts/XXX.com/htdocs/omeka/index.php(21): Zend\Mvc\Application->run()
#15 {main}

Je teste en desactivant les modules un peu plus tard
Merci encore

**Comment by ManOnDaMoon** [comment]
Ah, cette nouvelle erreur concerne bien RestrictedSite : c’est comme s’il manquait le nom du site dans l’URL. Quelle est l’Url en cause et le moyen précis d’y parvenir ?

**Comment by Caniaris** [comment]
L'URL est la suivante 
http://XXX.com/omeka/sitelogin/monsite
J’arrive a une page d'authentification sur le site concerné
Je m'identifie avec mon profil admin
L'URL reste la même et j'obtiens le message d'erreur précédemment envoyé que je sois admin ou invité.
La différence se situe après : quand je suis connecté en admin, une fois le message d'erreur apparu, comme je suis dans le site, lorsque je clique sur une des pages du site, elle s'affiche. Alors que quand je suis invité,  c'est la seconde erreur qui est renvoyée ( Entity of type 'Omeka\Entity\Item' for IDs id(8374) was not found)
A noter que l'adresse de mon site est en fait : http://XXX.com/omeka/s/monsite/page/XXX . L'erreur ne vient elle pas de la?
Merci
Yoann

**Comment by ManOnDaMoon** [comment]
OK merci, je pense avoir trouvé la raison.

Dans le fichier `omeka-s/modules/RestrictedSites/src/Controller/Site/SiteLoginController.php`, à la ligne 97, il faut remplacer :
`return $this->redirect()->toRoute('site');`
par 
`return $this->redirect()->toRoute('site', array(
                        'site-slug' => $siteSlug
                    ));`

Je ne peux pas mettre à jour le plugin dans l'immédiat, mais si tu ne peux pas effectuer la modification et la tester, je pusherai ces changements ce week-end.

**Comment by ManOnDaMoon** [comment]
> A noter que l'adresse de mon site est en fait : http://XXX.com/omeka/s/monsite/page/XXX . L'erreur ne vient elle pas de la?

Non, l'erreur viendrait plutôt d'un cas mal traité dans le module, pour lequel le nom du site n'est pas passé en paramètre.

**Comment by Caniaris** [comment]
J'ai effectué la modif dans "SiteLoginController.php"
Maintenant quand je me connecte en admin c'est bon, j'atterris directement sur le site qui fonctionne normalement.
Quand je me connecte en tant qu’invité, je n'ai plus l'erreur précédente (Zend\Router\Exception\InvalidArgumentException
Missing parameter "site-slug")

Mais on revient a lerreur NB 2 :

Doctrine\ORM\EntityNotFoundException
Entity of type 'Omeka\Entity\Item' for IDs id(8374) was not found

Si je comprends bien ça ne dépendrait pas de RestrictedSites mais plus de la base de données Omeka?
Merci
Yoann

**Comment by ManOnDaMoon** [comment]
OK

Oui l’erreur 2 vient d’ailleurs. Regarde si tu n’as pas un block « item showcase » sur une page (page d’accueil ?) qui serait configuré avec un contenu qui a été supprimé depuis, ou avec un mauvais ID. Et sinon adresse toi au forum Omeka qui sera plus compétent que moi pour déchiffrer cette erreur.
