### ISSUE TITLE
RestrictedSites et CSS Editor

### ISSUE THREAD

**Issue by Dominique56** [ManOnDaMoon/omeka-s-module-RestrictedSites#5]
J'arrive sur une page https://XXXX/ged/s/collections-marcophiles/css-editor blanche
quand j'activer CSS Editor

Version Omeka S 3.02
Voici les modules installés
Advanced Search Plus version 3.3.5.4
Any Cloud version 2.0.0 p
Block Plus version 3.3.11.6 
Blocks Disposition version 3.3.2.2 
Contact us and report version 3.3.8.4 
CSSEditor version 1.3.0 
Custom Vocab version 1.3.1 
Generic module version 3.3.28 
Group version 3.3.4.1 
Guest version 3.4.11.3
Guest Api version 3.3.3.3.3 
Iiif Search version 3.3.2.1 
IIIF Server version 3.6.3.2
Image Server version 3.6.5.3 
Item Sets Tree version 0.3.0 
ItemCopy version 1.0.1 
Mapping version 1.4.0 
Metadata Browse version 1.4.0 
Next version 3.3.39 
Pdf Viewer version 3.3.4.2
RestrictedSites version 2.0 
Search version 3.5.20.3 
Search History version 3.3.0.2 
Universal Viewer version 3.6.4.4
ViewerJS version 3.3.0.2 
Merci de votre assistance
Cordialement

**Comment by ManOnDaMoon** [comment]
Bonjour

Pouvez-vous me décrire la marche exacte à suivre pour reproduire le problème : chaque page visitée avec son adresse et l’action effectuée ? Par exemple si j’ai compris le souci :
- Page d’accueil http://xxxx/s/ged/page/accueil : clic sur « Se Connecter »
- Page de connexion http://xxxx/sitelogin/ged : renseignement du nom d’utilisateur et mot de passe, clic sur Connexion
- Arrivée sur la page http://xxx/s/ged/css-editor qui renvoie une erreur


Aussi pour vérifier quelles sont les interactions entre les modules, pouvez vous :
- désactiver tous les modules SAUF CSSEditor et Restrictedsites et vérifier que le problème persiste ?
- si le problème a disparu, réactiver les modules un par un en vérifiant à chaque fois si le problème réapparaît ?

J’ai réussi à utiliser les deux modules ensembles sans souci mais le problème est peut être plus complexe. Ces éléments me permettront d’en savoir plus. 

Bonne fin de journée

Laurent

**Comment by Dominique56** [comment]
Bonjour
J'ai désactivé tous les modules SAUF CSSEditor et Restrictedsites et l'erreur persiste.
La démarche n'est pas exactement celle que vous décrivez
1 - Je vais sur la page https://xxxxx/ged/s/accueil/page/accueil site ouvert au public
2 - J'ai mis un lien vers le site privé https://xxxx/ged/sitelogin/site-privé
3 - J'obtiens la page suivante 

Omeka S a rencontré une erreur
Pour obtenir plus d’informations à propos de cette erreur, consultez le manuel utilisateur Omeka S : récupérer les messages d’erreur

Par contre, si je vais sur la page https://xxxxx/ged/login
j'obtiens après saisie du login une page blanche intitulée https://xxxxxx/ged/s/site-privé/css-editor
et si j'efface /css-editor, j'arrive sur le site en étant bien connecté
Merci de votre réponse
Cordialement

**Comment by ManOnDaMoon** [comment]
Merci pour ces précisions.

Attention à l'étape 2, le site `site-privé` doit être visible par le public : l'icône en forme d'oeil en haut de la page http://xxx/ged/admin/site/s/site-privé#site-settings ne doit pas être barré. Pouvez-vous me le confirmer ?

J'ai besoin d'avoir plus de détails sur l'erreur à l'étape 3. Pour ce faire, il vous faut modifier le fichier `.htaccess` qui se trouve dans le répertoire principal d'Omeka S :
- trouver la première ligne qui indique `SetEnv APPLICATION_ENV "production"` et la modifier comme suit : `SetEnv APPLICATION_ENV "development"`
([instructions en anglais](https://omeka.org/s/docs/user-manual/errorLogging/#display-error-details))

Maintenant l'erreur affichée devrait être plus détaillée. Pouvez-vous me copier-coller ce détail ?
Une fois le message noté, pensez à rétablir le fichier .htaccess dans sa version d'origine.

Enfin, sur la dernière étape cela semble être un autre problème, car vous ne naviguez pas sur les pages spécifiques du module RestrictedSites. J'attends de voir les réponses aux questions ci-dessus pour savoir si tout ça est bien lié.

Laurent

**Comment by Dominique56** [comment]
Bonjour,
Le site-privé est visible du public
Voici le message d'erreur affiché sur la page
 Laminas\View\Exception\RuntimeException
Laminas\View\Renderer\PhpRenderer::render: Unable to render template "restricted-sites/site/site-login/login"; resolver could not resolve to a file

Détails :

Laminas\View\Exception\RuntimeException: Laminas\View\Renderer\PhpRenderer::render: Unable to render template "restricted-sites/site/site-login/login"; resolver could not resolve to a file in../ged/vendor/laminas/laminas-view/src/Renderer/PhpRenderer.php:497
Stack trace:
#0 .../ged/vendor/laminas/laminas-view/src/View.php(206): Laminas\View\Renderer\PhpRenderer->render(NULL)
#1 ..../ged/vendor/laminas/laminas-view/src/View.php(235): Laminas\View\View->render(Object(Laminas\View\Model\ViewModel))
#2 ....../ged/vendor/laminas/laminas-view/src/View.php(199): Laminas\View\View->renderChildren(Object(Laminas\View\Model\ViewModel))
#3 ....../ged/vendor/laminas/laminas-mvc/src/View/Http/DefaultRenderingStrategy.php(104): Laminas\View\View->render(Object(Laminas\View\Model\ViewModel))
#4 ......./ged/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\View\Http\DefaultRenderingStrategy->render(Object(Laminas\Mvc\MvcEvent))
#5 ....../ged/vendor/laminas/laminas-eventmanager/src/EventManager.php(170): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent))
#6 ......./ged/vendor/laminas/laminas-mvc/src/Application.php(366): Laminas\EventManager\EventManager->triggerEvent(Object(Laminas\Mvc\MvcEvent))
#7 ......../ged/vendor/laminas/laminas-mvc/src/Application.php(347): Laminas\Mvc\Application->completeRequest(Object(Laminas\Mvc\MvcEvent))
#8 ......./ged/index.php(21): Laminas\Mvc\Application->run()
#9 {main}

Cordialement

**Comment by ManOnDaMoon** [comment]
Omeka ne trouve pas le fichier suivant :
`modules/RestrictedSites/view/restricted-sites/site/site-login/login.phtml`
Pouvez-vous vérifier qu'il existe bien sur le serveur ?

S'il est absent : il faut réinstaller le module.
- supprimer le répertoire RestrictedSites
- télécharger à nouveau la v2.0 et la décompresser dans le répertoire `modules`

S'il est présent : les permissions sur les répertoires sont probablement erronées, il faut que les répertoires soient accessibles en exécution (traversables). Vous devrez exécuter un chmod 755 sur les répertoires du module:
- `chmod 755 $(find modules/RestrictedSites -type d)`

Si vous n'êtes pas familier avec cette instruction, alors le mieux est peut-être là aussi de réinstaller le module comme précisé plus haut.

**Comment by Dominique56** [comment]
Effectivement le fichier était absent.
J'ai réinstallé le plugin et ensuite j'arrive bien sur la page de login
mais j'obtiens après saisie du login une page blanche intitulée https://xxxxxx/ged/s/site-privé/css-editor
Cordialement

**Comment by ManOnDaMoon** [comment]
Je doute qu'on touche à un souci du module RestrictedSites en lui-même mais cela va devenir difficile d'en savoir plus sans avoir accès à un environnement où je peux reproduire l'erreur. Si vous avez la possibilité de partager un site de test par exemple ce serait utile.

Utilisez-vous bien Apache ? Si vous désactivez uniquement RestrictedSites seul et que vous tentez de vous connecter via https://xxxxx/ged/login avez-vous toujours le même souci ?

**Comment by Dominique56** [comment]
Après désactivation du module RestrictedSites et en me connectant via https://xxxxx/ged/login j'arrive sur la page https://xxxxx/ged/admin

Le site est hébergé chez O2switch

**Comment by ManOnDaMoon** [comment]
Et si vous désactivez uniquement CSSEditor ? Cela peut-être intéressant de réessayer l'installation de ce module également.

Pour savoir si vous utilisez Apache, il faut m'indiquer :
- le contenu de la page http://xxxx/ged/admin/system-info
- les headers HTTP : dans Chrome par exemple :
  1) Sur n'importe quelle page du site, faites un clic droit et sélectionnez "Inspecter". Dans la fenêtre qui s'ouvre choisissez l'onglet "Network" ou "Réseau"
  2) rechargez la page et cliquez sur le premier élément dans le volet de gauche. 
  3) Copiez-collez le contenu du volet de droite


![](https://mkyong.com/wp-content/uploads/2016/01/view-header-in-chrome.png)

**Comment by ManOnDaMoon** [comment]
Ignorez mes dernières demandes. Je viens de réussir à reproduire l'erreur.

Je regarde comment corriger ça.

**Comment by ManOnDaMoon** [comment]
J'ai publié une nouvelle version du module qui devrait résoudre le problème. Pouvez-vous l'installer et me confirmer que c'est réglé ?

**Comment by Dominique56** [comment]
Bonjour
Je viens d'installer la nouvelle version et le souci a disparu.
Merci pour votre recherche
Cordialement

**Comment by ManOnDaMoon** [comment]
Merci d’avoir signalé le problème et pour les détails fournis.
